### ISSUE TITLE
App is incompatible with Wine

### ISSUE THREAD

**Issue by luke512** [CriticalFlaw/FlawHUD.Installer#9]
Opening with wine doesn't seem to cause any other problems, but the entire window is white. I have seen a very similar issue with custom GUI and it looks like that is what you are doing, so maybe it wouldn't have this issue if it used the native windows UI. 

Sorry that I don't know too much about this. Also I completely understand if you don't care about supporting wine

**Comment by CriticalFlaw** [comment]
I would try and fix it but I don't have the environment set up to do so. I'll dig around the .NET Core documentation and see if there are any mentions of compatibility with wine. If anyone else wants to fix this they are welcome to open a PR.

**Comment by CriticalFlaw** [comment]
https://appdb.winehq.org/objectManager.php?sClass=application&iId=2586

**Comment by CriticalFlaw** [comment]
The app is built in .NET Framework 4.8 which looks to be woefully functional in wine. I've been wanting to rebuild it in .NET Core because it's newer and will hopefully have better cross-platform computability. I'll create a separate build of it and you can try it out and let me know if it's any better.

https://appdb.winehq.org/objectManager.php?sClass=application&iId=2586

**Comment by CriticalFlaw** [comment]
Give this release a try and see if it's any better or worse.

https://github.com/CriticalFlaw/FlawHUD.Installer/releases/tag/1.5.Test

**Comment by luke512** [comment]
It seems like the entire app functionally works perfectly. Most graphics are displayed correctly, except that check boxes don't display whether they are ticked. They do toggle since clicking "Enable Crosshair" causes the options next to it to enable and disable.
